### ISSUE TITLE
Error 110

### ISSUE THREAD

**Issue by zQueal** [BertoldVdb/sdtool#12]
┌ ~
    └> % sdtool /dev/mmcblk0 unlock                                                                                        
    [-] Failed to open MMC block device: Permission denied
    ┌ 1 ~
    └> % please                                                                                                            
    [+] Found RCA for /dev/mmcblk0: AAAA.
    Error 110
    [-] Failed to send command: Connection timed out

I inserted my sd card, and ran after compiling. Unfortunately, there's no other information whatsoever to go on. What is error 110?

I've tried flipping the physical write protection for the sd card on the adapter, I get this error both times.

I tried with a card that is 1 day old and I know to be working fine. No matter the position of the physical write protection slider, I get error 110.

    ┌ ~
    └> % sudo sdtool /dev/mmcblk0 unlock                                                                              
    [+] Found RCA for /dev/mmcblk0: 0001.
    Error 110
    [-] Failed to send command: Connection timed out

What's going on here?

**Comment by LLinoor** [comment]
The developer is aware of the bug here's his answer: https://github.com/BertoldVdb/sdtool/issues/10#issuecomment-660961315

**Comment by zQueal** [comment]
Interesting. For anyone wondering, I'm running Arch with 5.7.10 kernel.

![20200729_015507_tzq](https://user-images.githubusercontent.com/239193/88762074-763b5980-d13e-11ea-8564-8d72e185e0b5.png)

**Comment by rustybird** [comment]
Looks like this (and #10 too, I assume) was fixed in the kernel at some point: sdtool with kernel 5.10.8 has started working again.
