### ISSUE TITLE
no mmcblk* devices on system, even with SD card mounted

### ISSUE THREAD

**Issue by jelabarre59** [BertoldVdb/sdtool#14]
On Fedora 33, the microSD card is mounting the device from /dev/sde# to /run/media/user/boot, but no block device shows at  /dev/mmcblk* .  I'm presuming the newer version of Fedora is using a different location now, and won't show the path you are looking for.

**Comment by BertoldVdb** [comment]
Most likely your system is using an SD-bridge that exposes the card as a mass storage device over USB, these can't be used with this code. You need a native interface.
