### ISSUE TITLE
mmc0: error -110 whilst initialising SD card

### ISSUE THREAD

**Issue by mlpd** [BertoldVdb/sdtool#16]
After locking the SD Card (my device has a slot for SD/mmc card -- not using a USB adapter), the sd card no longer "works".
Running Linux ubuntu 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
After plugging the SD card in nothing happens.
I cannot run the unlock command as I get the following error: Failed to open MMC block device: No such device or address
It no longer shows up under /dev/mmcblk* (previously insertion would create /dev/mmcblk0).
Dmesg shows : mmc0: error -110 whilst initialising SD card

Unlocked SD cards continue to work. 

The closest thing I could find was this issue from a similar tool: 
https://github.com/alcooper/mmc-password-utils/issues/1

thanks!

**Comment by sangh** [comment]
Try again using a 6.1.0 kernel.
