### ISSUE TITLE
Found RCA for /dev/mmcblk0: 59B4.  Error 110

### ISSUE THREAD

**Issue by DrRob** [BertoldVdb/sdtool#17]
Running on a Pi Zero W under PiCore:

```
$ sudo ./arm-sdtool /dev/mmcblk0 status
[+] Found RCA for /dev/mmcblk0: 59B4.
Error 110
[-] Failed to send command: Operation timed out
```

This used to work, so does this indicate that my micro SD card has become faulty?

**Comment by sangh** [comment]
Try this again on a newer Raspbian (based on bookworm and a 6.1.0 kernel).
