### ISSUE TITLE
Says directory doesn't exist

### ISSUE THREAD

**Issue by innocous06** [BertoldVdb/sdtool#19]
So I was trying to remove the temp write protection from my micro sd so I used manjaro Linux and installed sdtool using yay , but then it wasn't showing the SD card named as **mmcblk** or somethin but was showing **sda** or **sdb** , is there something wrong with installation of sdtool or what ,
Also I tried to replace the mmcblk0*p or whatever you told about in the readme , I replaced it with sda or sdb as it was showing when I used the command listing the drives, but then it said that such directory doesn't exist , what to do !? @wamserma @BertoldVdb @Remi-p #14 
[I first reffered to this post](https://www.quora.com/How-can-I-format-my-expired-BYJU-s-SD-card-I-tried-CMD-but-it-didn-t-work-and-I-m-unable-to-remove-write-protection/answer/Sia-Del-1?comment_id=385841400&comment_type=2)

**Comment by innocous06** [comment]
And just to tell you I am new to Linux and such low level coding , please lead this newbie

**Comment by wamserma** [comment]
This is not specific to sdtool. SD-Card-readers can use different connection types ("cables") inside the computer. The MMC type shows up as mmcblk, most others as sdX. The commands to set/unset the temp write protection can only be transferred on the MMC type. You need to find a different card reader/computer.

**Comment by innocous06** [comment]
> This is not specific to sdtool. SD-Card-readers can use different connection types ("cables") inside the computer. The MMC type shows up as mmcblk, most others as sdX. The commands to set/unset the temp write protection can only be transferred on the MMC type. You need to find a different card reader/computer.

Thanks , just asking like currently I am using micro sd to sd converter , does micro sd to usb work ?? Like does micro sd to usb gets read as mmc type or not !?

**Comment by wamserma** [comment]
The converter just changes the Location of the connectors, not their number or the "language" that is spoken on these lines. USB-Adapters usually do not speak the MMC protocol.

**Comment by innocous06** [comment]
> The converter just changes the Location of the connectors, not their number or the "language" that is spoken on these lines. USB-Adapters usually do not speak the MMC protocol.

Thanks maybe the SD card adaptor isn't making it work or the card reader of my laptop, btw is SDHC a mmc type !?

**Comment by wamserma** [comment]
The HC just denotes a range for the capacity. SD is an evolution of MMC, but some commands removed. Look for a card reader that accepts SD and MMC cards. Also be careful: When issuing the wrong commands, you might destroy your SD card.

**Comment by innocous06** [comment]
> The HC just denotes a range for the capacity. SD is an evolution of MMC, but some commands removed. Look for a card reader that accepts SD and MMC cards. Also be careful: When issuing the wrong commands, you might destroy your SD card.

![Screenshot_20240117_145055](https://github.com/BertoldVdb/sdtool/assets/78302731/8575624d-888b-4961-81f6-ad7ac7458823)
(The sdb and SDC are two diff sd cards with two different card readers I've used)
As you can see it's not recognising it as mmc , so ig I need to change my device , thanks for listening me out
