### ISSUE TITLE
Raspberry Pi SPI support

### ISSUE THREAD

**Issue by smythcc** [BertoldVdb/sdtool#4]
It doesn't appear this utility supports interacting with an SD card connected via the SPI pins on the GPIO header. I point it at `/dev/mmcblk2` but get a "Failed to send command: Function not implemented" response. Any thoughts on how this could be supported? (Possible driver/config issue?)

**Comment by BertoldVdb** [comment]
I think this command is not available when using the card in MMC (SPI) mode. Therefore it cannot be implemented.
