### ISSUE TITLE
still failing 

### ISSUE THREAD

**Issue by krishnasen2401** [BertoldVdb/sdtool#5]
after executing the command after reboot it still says lock in pc and rpi
this is the output
[+] Found RCA for /dev/mmcblk0: 59B4.
[+] CSD unchanged.
[+] Write protection state: Off.

**Comment by BertoldVdb** [comment]
Can you confirm me the exact command you executed?

To lock the card you need to do something like this:
sudo ./arm-sdtool /dev/mmcblk0 lock
where you replace ./arm-sdtool with the right path.

**Comment by krishnasen2401** [comment]
the directory is same as where it was cloned and i was trying to unlock or remove write protection of the SD Card instead of locking it and i gave Unlock Option instead ok lock after excuting the command its say unlocked when asked for the status but after reboot it again gets locked

**Comment by BertoldVdb** [comment]
Since the tool says the CSD is unchanged the card is not locked, at least not in a way that can be cleared by this program. Are you sure the mechanical switch is set correctly?
