### ISSUE TITLE
sdtool example write protects sd card but leaves card unbootable

### ISSUE THREAD

**Issue by kzamora1** [BertoldVdb/sdtool#7]
Love sdtool!  Works as advertised. However, when I write protected my linux raspberry image and  rebooted, I got errors. Is this because linux is trying to write to the sd and now that it is protected, the boot process fails?

I was hoping to protect the linux image from being corrupted but maybe that's not possible,

**Comment by BertoldVdb** [comment]
Hello,

This is expected. You should also configure your Linux system to use a read only filesystem. :)

Sincerely,
Bertold
